# Generated by Django 5.0.6 on 2025-04-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partners',
            old_name='logo',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='link',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='name',
        ),
    ]
