# Generated by Django 5.0.6 on 2025-04-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_rename_logo_partners_image_remove_partners_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
            ],
        ),
        migrations.RenameField(
            model_name='partners',
            old_name='image',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='partners',
            name='link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='partners',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
